name = "app-kopecode"
version = "0.0.1"
description = "Página kopecode"
type = "javascript"  # ou "module", se você estiver usando módulos ES6

account_id = "ae9f06f82327ec60d854cf65f08005c4"
workers_dev = true

# Especifique o caminho de saída do Astro
main = "./dist/server/entry.mjs"  # Atualize conforme o caminho do build do Astro
compatibility_date = "2023-10-26"
